version: "3.13"

services:
  backend:
    build:
      context: ./backend
    env_file:
    - .env
    container_name: chatbot-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: chatbot-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    restart: unless-stopped
